/**
 * Command: !aiimage
 * Generate Image from Text (Aritek AI)
 */
const { aiMultimedia } = require('../services/extraApiService');
const chalk = require('chalk');

module.exports = {
    name: 'aiimage',
    description: 'Buat gambar AI dari teks',
    async execute(sock, msgObj, context) {
        const { sender, args } = context;

        const prompt = (args || "").trim();
        if (!prompt) {
            await sock.sendMessage(sender, { 
                text: "Silakan masukkan deskripsi gambar yang ingin dibuat.\nContoh: !aiimage astronot naik kuda di bulan"
            }, { quoted: msgObj });
            return;
        }

        try {
            // Processing message
            await sock.sendMessage(sender, { 
                text: "⏳ Sedang memproses gambar Anda..."
            }, { quoted: msgObj });

            const res = await aiMultimedia.generate(prompt, 'image');
            
            if (res.success && res.url) {
                await sock.sendMessage(sender, { 
                    image: { url: res.url },
                    caption: `🖼️ *IMAGE GENERATED BY AI*\n\n*Prompt:* ${prompt}`
                }, { quoted: msgObj });
            } else {
                await sock.sendMessage(sender, { 
                    text: `❌ Gagal membuat gambar: ${res.error || "Server sedang sibuk"}`
                }, { quoted: msgObj });
            }

        } catch (e) {
            console.error('[CMD:AIIMAGE] Error:', e.message);
            await sock.sendMessage(sender, { 
                text: "⚠️ Terjadi kesalahan saat memproses gambar. Silakan coba lagi nanti."
            }, { quoted: msgObj });
        }
    }
};
