/**
 * Command: !aivideo
 * Generate Video from Text (Aritek AI)
 */
const { aiMultimedia } = require('../services/extraApiService');
const chalk = require('chalk');

module.exports = {
    name: 'aivideo',
    description: 'Buat video AI dari teks (Butuh waktu sekitar 1-2 menit)',
    async execute(sock, msgObj, context) {
        const { sender, args } = context;

        const prompt = (args || "").trim();
        if (!prompt) {
            await sock.sendMessage(sender, { 
                text: "Silakan masukkan deskripsi video yang ingin dibuat.\nContoh: !aivideo pemandangan sunset di pantai bali"
            }, { quoted: msgObj });
            return;
        }

        if (prompt.length < 5) {
            return m.reply("Prompt terlalu pendek (minimal 5 karakter).")
        }

        await sock.sendMessage(sender, { 
            text: "⏳ Sedang memproses video Anda. Mohon bersabar, ini memakan waktu sekitar 1-2 menit..."
        }, { quoted: msgObj });

        try {
            const res = await aiMultimedia.generate(prompt, 'video');
            
            if (res.success && res.url) {
                await sock.sendMessage(sender, { 
                    video: { url: res.url },
                    caption: `🎬 *VIDEO GENERATED BY AI*\n\n*Prompt:* ${prompt}`
                }, { quoted: msgObj });
            } else {
                await sock.sendMessage(sender, { 
                    text: `❌ Gagal membuat video: ${res.error || "Server sedang sibuk"}`
                }, { quoted: msgObj });
            }

        } catch (e) {
            console.error('[CMD:AIVIDEO] Error:', e.message);
            await sock.sendMessage(sender, { 
                text: "⚠️ Terjadi kesalahan saat memproses video. Silakan coba lagi nanti."
            }, { quoted: msgObj });
        }
    }
};
